set_property SRC_FILE_INFO {cfile:/home/labish/Midget/SKL/FPGA_Flash_BKUP/Notion_DEMO.srcs/constrs_1/new/Demo.xdc rfile:../../../Notion_DEMO.srcs/constrs_1/new/Demo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports {o_LED_0[3]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports {o_LED_0[2]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {o_LED_0[1]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {o_LED_0[0]}]
