# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Demo.xdc

# Block Designs: bd/DEMO/DEMO.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO || ORIG_REF_NAME==DEMO} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO_processing_system7_0_0 || ORIG_REF_NAME==DEMO_processing_system7_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_LED_Connector_v1_0_0_0/DEMO_LED_Connector_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO_LED_Connector_v1_0_0_0 || ORIG_REF_NAME==DEMO_LED_Connector_v1_0_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_PL_SPI_DDS_v1_0_0_0/DEMO_PL_SPI_DDS_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO_PL_SPI_DDS_v1_0_0_0 || ORIG_REF_NAME==DEMO_PL_SPI_DDS_v1_0_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO_xbar_0 || ORIG_REF_NAME==DEMO_xbar_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_ps7_0_axi_periph_0/DEMO_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO_ps7_0_axi_periph_0 || ORIG_REF_NAME==DEMO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rst_ps7_0_50M_0/DEMO_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO_rst_ps7_0_50M_0 || ORIG_REF_NAME==DEMO_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_auto_pc_0/DEMO_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DEMO_auto_pc_0 || ORIG_REF_NAME==DEMO_auto_pc_0} -quiet] -quiet

# XDC: /home/labish/Midget/SKL/FPGA_Flash_BKUP/Notion_DEMO.gen/sources_1/bd/DEMO/DEMO_ooc.xdc
